blog/user/views.py
from flask import Blueprint, render_template
from blog.models import User, Article
from flask_login import login_required, current_user

user_app = Blueprint('user_app', __name__, static_folder='../static', url_prefix='/users')


@user_app.route('/')
@login_required
def user_list():
    users = User.query.all()
    return render_template(
        'user/list.html',
        users=users,
    )


@user_app.route('/<int:user_id>/')
@login_required
def user_profile(user_id: int):
    try:
        user = User.query.filter_by(id=user_id).one_or_none()
        articles = Article.query.filter_by(author_id=user_id)
    except KeyError:
        raise FileNotFoundError(f'User id {user_id} not found')



    if current_user.is_staff is True:
        return render_template(
            'user/detail.html',
            user=user,
            articles=articles
        )
    else:
        error = 'this is staff area only'
        return render_template(
            'user/list.html',
            user=user,
            error=error,
        )

blog/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    {% endblock %}
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
    {% block body %}{% endblock %}
</div>
{% block javascript %}
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
{% endblock %}
</body>
</html>

blog/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Welcome to blog
{% endblock %}

{% block body %}
    <h1 class="mt-5 mb-5">Users:</h1>
    <h1>
        Hello
        {% if current_user.is_authenticated %}
            {{ current_user.username }}
        {% else %}
            anon
        {% endif %}
    </h1>
{% endblock %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user_app.user_list') }}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('authors_app.list') }}">Authors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('articles_app.list') }}">Articles</a>
                </li>
            </ul>
{#            <form class="d-flex" role="search">#}
{#                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
{#                <button class="btn btn-outline-success" type="submit">Search</button>#}
{#            </form>#}
            <div class="navbar-nav ms-auto">
                {% if current_user.is_staff %}
                    <a class="nav-link" href="{{ url_for('api-docs.openapi_swagger_ui') }}">Api Swagger</a>
                    <a class="nav-link" href="{{ url_for('admin.index') }}">Admin Panel</a>
                {% endif %}
                {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('auth_app.logout') }}">{{ current_user.username }} Logout</a>
                {% else %}
                    {% for (endpoint, label) in [('auth_app.login', 'Login'), ('auth_app.register','Register')] %}
                        <a href="{{ url_for(endpoint) }}"
                           class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
                            {{ label }}
                        </a>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</nav>