blog/models/article.py
from sqlalchemy import Column, Integer, ForeignKey, String, Text, DateTime, func
from sqlalchemy.orm import relationship
from datetime import datetime

from blog.models.database import db
from blog.models.article_tag import article_tag_association_table


class Article(db.Model):
    id = Column(Integer, primary_key=True)
    author_id = Column(Integer, ForeignKey("author.id"))
    author = relationship("Author", back_populates="articles")
    title = Column(String(200), nullable=False, default="", server_default="")
    body = Column(Text, nullable=False, default="", server_default="")
    dt_created = Column(DateTime, default=datetime.utcnow, server_default=func.now())
    dt_updated = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    tags = relationship(
        "Tag",
        secondary=article_tag_association_table,
        back_populates="articles",
    )

    def __str__(self):
        return self.title

blog/forms/article.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, validators, SelectMultipleField


class CreateArticleForm(FlaskForm):
    title = StringField(
        "Title",
        [validators.DataRequired()],
    )
    body = TextAreaField(
        "Body",
        [validators.DataRequired()],
    )
    tags = SelectMultipleField("Tags", coerce=int)
    submit = SubmitField("Publish")

blog/articles/views.py
from flask import Blueprint, render_template, request, current_app, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy.exc import IntegrityError
from werkzeug.exceptions import NotFound
from sqlalchemy.orm import joinedload

from blog.models.database import db
from blog.models import Author, Article, Tag, User
from blog.forms.article import CreateArticleForm

articles_app = Blueprint('articles_app', __name__, url_prefix='/articles')


@articles_app.route("/", endpoint="list")
@login_required
def articles_list():
    articles = Article.query.all()
    return render_template("articles/list.html", articles=articles)


@articles_app.route("/tag/<int:tag_id>/", endpoint="list_by_tag")
@login_required
def articles_list_by_tag(tag_id):
    tag = Tag.query.filter_by(id=tag_id).options(joinedload(Tag.articles)).one_or_none()
    if tag is None:
        raise NotFound
    return render_template("articles/articles_by_tag.html", tag=tag)


@articles_app.route("/<int:article_id>/", endpoint="details")
def article_detals(article_id):
    article = Article.query.filter_by(id=article_id).options(
        joinedload(Article.tags)  # подгружаем связанные теги!
    ).one_or_none()
    if article is None:
        raise NotFound
    return render_template("articles/detail.html", article=article)


@articles_app.route("/create/", methods=["GET", "POST"], endpoint="create")
@login_required
def create_article():
    error = None
    form = CreateArticleForm(request.form)
    # добавляем доступные теги в форму
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by("name")]
    if request.method == "POST" and form.validate_on_submit():  # при создании статьи
        article = Article(title=form.title.data.strip(), body=form.body.data)
        if form.tags.data:  # если в форму были переданы теги (были выбраны)
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
        for tag in selected_tags:
            article.tags.append(tag)  # добавляем выбранные теги к статье
        if current_user.author:
            # use existing author if present
            article.author = current_user.author
        else:
            # otherwise create author record
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
            article.author = current_user.author
        try:
            db.session.add(article)
            db.session.commit()
        except IntegrityError:
            current_app.logger.exception("Could not create a new article!")
            error = "Could not create article!"
        else:
            return redirect(url_for("articles_app.details", article_id=article.id))
    return render_template("articles/create.html", form=form, error=error)

blog/user/views.py
from flask import Blueprint, render_template
from blog.models import User, Article
from flask_login import login_required, current_user

user_app = Blueprint('user_app', __name__, static_folder='../static', url_prefix='/users')


@user_app.route('/')
@login_required
def user_list():
    users = User.query.all()
    return render_template(
        'user/list.html',
        users=users,
    )


@user_app.route('/<int:user_id>/')
@login_required
def user_profile(user_id: int):
    try:
        user = User.query.filter_by(id=user_id).one_or_none()
        articles = Article.query.filter_by(author_id=user_id)
    except KeyError:
        raise FileNotFoundError(f'User id {user_id} not found')



    if current_user.is_staff is True:
        return render_template(
            'user/detail.html',
            user=user,
            articles=articles
        )
    else:
        error = 'this is staff area only'
        return render_template(
            'user/list.html',
            user=user,
            error=error,
        )

blog/templates/articles/articles_by_tag.html
{% extends 'base.html' %}

{% block title %}
    Articles list by tag {{ tag.name }}
{% endblock %}

{% block body %}
    <div>
        {% if tag.articles %}
            <h1 class="mt-5 mb-5">Articles by tag: {{ tag.name }}</h1>
            <ul>
                {% for article in tag.articles %}
                    <li>
                        <a href="{{ url_for('articles_app.details', article_id=article.id) }}">{{ article.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

blog/templates/articles/create.html
{% extends 'base.html' %}
{% block title %}
    Create article
{% endblock %}
{% block body %}
    <h1 class="mt-5 mb-5">Create article</h1>
    <div>
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        <form method="post">
            {{ form.csrf_token }}
            {% for field_name in ['title', 'body', 'tags'] %}
                {% set field = form[field_name] %}
                <div class="my-3">
                    {{ field.label(class="form-label") }}
                    {{ field(class="form-control") }}
                </div>
            {% endfor %}
            {{ form.submit(class="btn btn-primary my-3") }}
        </form>
    </div>
{% endblock %}

blog/templates/articles/detail.html
{% extends 'base.html' %}
{% block title %}
    Article #{{ article.id }}: {{ article.title }}
{% endblock %}
{% block body %}
    <h1 class="mt-5 mb-5">{{ article.title }}</h1>
    <div>
        <p>{{ article.body }}</p>
        {% if article.tags %}
            <div>Tags:</div>
            <ul>
                {% for tag in article.tags %}
                    <li>
                        <a href="{{ url_for('articles_app.list_by_tag', tag_id=tag.id) }}">{{ tag.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        <div>Published {{ article.dt_created.strftime('%d, %b %Y') }}</div>
        <div>
            <a href="{{ url_for('user_app.user_profile', user_id=article.author_id) }}">
                by {{ article.author.user.username }}</a>
        </div>

    </div>
{% endblock %}

blog/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}
    Articles list
{% endblock %}

{% block body %}
    <h1 class="mt-5 mb-5">Articles:</h1>
    <div>
        <ul>
            {% for article in articles %}
                <li>
                    <a href="{{ url_for('articles_app.details', article_id=article.id) }}">{{ article.title }}</a>
                    by {{ article.author.user.username }}
                </li>
            {% endfor %}
        </ul>
        <hr>
        <a href="{{ url_for('articles_app.create') }}">Create new</a>
    </div>
{% endblock %}