blog/models/author.py
from sqlalchemy import Column, Integer, ForeignKey
from sqlalchemy.orm import relationship

from blog.models.database import db


class Author(db.Model):
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("user.id"), nullable=False)
    user = relationship("User", back_populates="author")
    articles = relationship("Article", back_populates="author")

    def __str__(self):
        return self.user.username

blog/authors/views.py
from flask import Blueprint, render_template
from flask_login import login_required
from blog.models import Author, Article

authors_app = Blueprint("authors_app", __name__)


@authors_app.route("/", endpoint="list")
@login_required
def authors_list():
    authors = Author.query.all()
    return render_template("authors/list.html", authors=authors)


@authors_app.route('/<int:author_id>/')
@login_required
def author_profile(author_id: int):
    try:
        author = Author.query.filter_by(id=author_id).one_or_none()
        articles = Article.query.filter_by(author_id=author_id)
    except KeyError:
        raise FileNotFoundError(f'Author id {author_id} not found')

    return render_template(
        'authors/detail.html',
        author=author,
        articles=articles
    )

blog/templates/authors/detail.html
{% extends 'base.html' %}

{% block title %}
    Author #{{ author.user.username }}
{% endblock %}

{% block body %}
    <h1 class="mt-5 mb-5">Author detail:</h1>
    <div class="row">
        <div class="col-3">
            <h5>Author:</h5>
            <p>{{ author.user.username }}</p>
            <p>{{ author.user.first_name }}</p>
            <p>{{ author.user.last_name }}</p>
        </div>
    </div>

    {% if articles[0] %}
        <div><h5>Author Articles:</h5>
            {% for article in articles %}
                <ul>
                    <li><a href="{{ url_for('articles_app.details', article_id=article.id) }}">
                        {{ article.title }} | {{ article.dt_created.strftime('%d, %b %Y') }}</a></li>
                </ul>
            {% endfor %}
        </div>
    {% endif %}

{% endblock %}

blog/templates/authors/list.html
{% extends 'base.html' %}
{% block title %}
    Authors list
{% endblock %}
{% block body %}
    <h1 class="mt-5 mb-5">Authors</h1>
    <div>
        {% if authors %}
            <ul>
                {% for author in authors %}
{#                    <li>#}
{#                        #{{ author.id }} ({{ author.user.username }})#}
{#                    </li>#}
                    <li><a href="{{ url_for('authors_app.author_profile', author_id=author.id) }}">{{ author.user.username }}</a>
                        {% if author.user.is_staff %}
                            <span class="badge bg-secondary">staff</span>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <h3>No authors yet</h3>
        {% endif %}
    </div>
{% endblock %}